package com.moulik.exception;

/**
 * Following are the commonly used methods from Exception class.
 * 
 * String getMessage(): Returns a detailed message about the exception that has occurred
 * String getLocalizedMessage(): Returns a localized description of the exception
 * 
 * Throwable getCause(): Returns the cause of the exception as represented by a Throwable object.
 * Throwable initCause(Throwable causeExc): Associates causeExc with invoking exception as a cause of invoking exception. Returns a reference to the exception.
 * String toString(): Returns the name of the class concatenated with the result of getMessage()
 * 
 * void printStackTrace(): Prints the result of toString() along with the stack trace to System.err, the error output stream.
 * StackTraceElement [] getStackTrace(): Returns an array containing each element on the stack trace. 
 * void setStackTrace(StackTraceElement elements[]): Sets the stack trace to the elements passed in elements. This method is for the specialized applications,
 * 		not normal use
 * Throwable fillInStackTrace(): Fills the stack trace of this Throwable object with the current stack trace, adding to any previous information in stack trace.
 * 		This object can be re-thrown.
 * 
 * final Throwable[] getSuppressed(): Obtains the suppressed exceptions associated with the invoking exception and returns an array that contains the result. 
 * 		Suppressed exceptions are primarily generated by the try-with-resources statement
 *
 */
public class ExceptionMethodsDemo {

	public static void main(String[] args) {

	}

}
